### ISSUE TITLE
Package cannot be added as a dynamic library

### ISSUE THREAD

**Issue by MMise** [BB9z/LAME-xcframework#1]
It is not possible to add this package as a `dynamic` library through SPM. I have been using this package for a long time (version 3.100.0). After updating to version 3.100.1 I get an error `dyld: Library not loaded: /Library/Frameworks/LAME.framework/LAME`. After some investigation I found out you should change:

```
products: [
        .library(name: "LAME", targets: ["LAME"])
],
```

to:

```
products: [
        .library(name: "LAME", type: .dynamic, targets: ["LAME"])
    ],
```

in `Package.swift` of this package

**Comment by BB9z** [comment]
Got it, I will take a look this weekend.

**Comment by BB9z** [comment]
This is weird, I can't even get the dynamic library works successfully locally. Needs further investigation.

As far as I know, `type: .dynamic` is not required:
https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages

**Comment by BB9z** [comment]
I know what went wrong. Give me some time to make sure it's all right this time.

**Comment by BB9z** [comment]
@MMise 3.100.2 should work, try it out.

**Comment by MMise** [comment]
Seems to work now!

**Comment by HanochZhu** [comment]
The problem still exist in 3.1000.2. After add package thought SPM. APP has crash, and get `dyld[5614]: Library not loaded: @rpath/LAME.framework/LAME` 

After add this package, do I need to do other operations for it to run correctly?
